config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :employees do
    resources :accounts
  end
  
  get "welcome/index"

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  get 'welcome/pricing'

  get 'welcome/features'
  
 
  
  resources :invoices

  root to: 'welcome#index'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artcompany</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    
<div class="container">
   <ul class="nav nav-tabs">
  
         <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "About Us", welcome_about_path %></li>
         <li><%= link_to "Contact", welcome_contact_path %></li>
         <li><%= link_to "Features", welcome_features_path %></li>
         <li><%= link_to "FAQs", welcome_faq_path %></li>
         <li><%= link_to "Pricing", welcome_pricing_path %></li>
         
         
         <% if current_user %>
             
                 <li><%= link_to "Sign Out", destroy_user_session_path, method: :get %></li>
        <div class='btn-group pull-right right-nav'>
                <button type="button" class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
                  
                  <span class="caret"></span>
                  <span clas="sr-only">Admin</span>
                
          </button>
               <ul class="dropdown-menu"  role="menu">
                   <li><%= link_to "Invoices", invoices_path %></li>
                 <li><%= link_to "Employees", employees_path %></li>
          </ul>
     </div>
            

         <% else %>
             <li><%= link_to "Sign Up", new_user_registration_path %></li>
             <li><%= link_to "Sign In", new_user_session_path %></li>
         <% end %>     
     
   </ul>
   
   
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

  <%= yield %>
  
</div>

</body>
</html>