config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :employees do
    resources :accounts
  end
  
  get "welcome/index"

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  get 'welcome/pricing'

  get 'welcome/features'
  
 
  
  resources :invoices

  root to: 'welcome#index'
  
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :employee, :foreign_key => "employee_id"
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  # GET /employee/1/account
  
  def index
    @employee = Employee.find(params[:employee_id])
    @account = @employee.account 
  end


  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @employee = Employee.find(params[:employee_id]) 
    @account = @employee.account 
  end

  # GET /employees/1/accounts/new 
  def new
    @employee = Employee.find(params[:employee_id])
    @account = @employee.build_account() 
  end
  


  # GET /accounts/1/edit
  # GET /customers/1/accounts/2/edit 
  def edit
    @employee = Employee.find(params[:employee_id])
    # the customer has only one account, therefore we directly # retrieve his account 
    @account = @employee.account 
  end
  
  # PATCH/PUT /customers/1/accounts/2 
  def update 
    @employee = Employee.find(params[:employee_id]) 
    @account = @employee.account 
    respond_to do |format| 
      if @account.update(account_params)
        format.html { redirect_to employee_account_url(@employee, @account),
        notice: 'Account was successfully updated.' } 
        format.json { render :show, status: :ok, location: @account } 
        else 
          format.html { render :edit } 
          format.json { render json: @account.errors, 
          status: :unprocessable_entity } 
      end
    end
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @employee = Employee.find(params[:employee_id]) 
    @account = @employee.build_account(account_params)


    respond_to do |format|
      if @account.save
       format.html { redirect_to employee_account_url(@employee, @account), notice: 'Account was successfully created.' }
       format.json { render :show, status: :created, location: @account } 
       else
         format.html { render :new } 
         format.json { render json: @account.errors, status: :unprocessable_entity } 
      end
    end
  end
  
 
  

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # DELETE /blogs/1/posts/2 
  def destroy 
    @employee = Employee.find(params[:employee_id])
    
    # the employee has only one account, therefore 
    # we directly retrieve his account 
    @account = @employee.account 
    @account.destroy 
    respond_to do |format| 
      format.html { redirect_to employee_accounts_url(@employee), 
        notice: 'Account was successfully destroyed.' } 
      format.json { head :no_content } 
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:address1, :address2, :comments, :details, :employee)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for([@employee, @account]) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.text_field :employee_id %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>


<%= link_to 'Show', employee_account_path(@employee, @account) %> 
<%= link_to 'Back', employee_accounts_path(@employee) %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Account for Customer 
<%= @employee.first_name %>
<%= @employee.last_name %>
</h1>

<!-- a customer can have 0 or 1 account--> 
<!-- if the customer does not have an account we cannot 
    display the account details as the application will crash--> 
<% if @account == nil %>
  <h3> This employee has no account yet. </h3> 
<% else %> 
  <!-- the account exists, let's display its details-->



<table>
  <thead>
    <tr>
      <th>Address1</th>
      <th>Address2</th>
      <th>Comments</th>
      <th>Details</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
      <tr>
        <td><%= account.address1 %></td>
        <td><%= account.address2 %></td>
        <td><%= account.comments %></td>
        <td><%= account.details %></td>
        <td><%= account.employee %></td>
        <td><%= link_to 'Show', employee_account_path(@employee, @account) %></td>
        <td><%= link_to 'Edit', edit_employee_account_path(@employee, @account) %></td>
        <td><%= link_to 'Destroy', employee_account_path(@employee, @account), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>

  <% end %>
  

<br>

<%= link_to 'New Account', new_employee_account_path(@employee) %>
<%= link_to 'Back to employee', @employee %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_accounts_path(@employee) %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address1:</strong>
  <%= @account.address1 %>
</p>
<p>
  <strong>Address1:</strong>
  <%= @account.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @account.address2 %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @account.comments %>
</p>

<p>
  <strong>Details:</strong>
  <%= @account.details %>
</p>



<%= link_to 'Edit', edit_employee_account_path(@employee, @account) %> |
<%= link_to 'Back', employee_accounts_path(@employee) %>